const EMOJI_SHORTCUTS: Record<string, string> = {
  // Faces
  happy: "😀",
  smile: "😀",
  feliz: "😀",
  laugh: "😂",
  lol: "😂",
  risa: "😂",
  love: "😍",
  amor: "😍",
  think: "🤔",
  hmm: "🤔",
  pensando: "🤔",
  cry: "😢",
  sad: "😢",
  triste: "😢",
  angry: "😠",
  enojado: "😠",
  cool: "😎",
  sunglasses: "😎",
  wink: "😉",
  guino: "😉",
  kiss: "😘",
  beso: "😘",
  sick: "🤒",
  enfermo: "🤒",
  crazy: "🤪",
  loco: "🤪",
  scared: "😱",
  asustado: "😱",
  devil: "😈",
  diablo: "😈",
  angel: "😇",

  // Gestures
  ok: "👍",
  good: "👍",
  yes: "👍",
  bien: "👍",
  bad: "👎",
  mal: "👎",
  clap: "👏",
  aplausos: "👏",
  wave: "👋",
  hello: "👋",
  bye: "👋",
  hola: "👋",
  adios: "👋",
  pray: "🙏",
  thanks: "🙏",
  gracias: "🙏",
  please: "🙏",
  strong: "💪",
  power: "💪",
  fuerza: "💪",
  punch: "👊",
  peace: "✌️",
  paz: "✌️",
  point: "👉",

  // Hearts & Symbols
  heart: "❤️",
  corazon: "❤️",
  fire: "🔥",
  fuego: "🔥",
  hot: "🔥",
  sparkles: "✨",
  magic: "✨",
  brillos: "✨",
  star: "⭐",
  estrella: "⭐",
  favorite: "⭐",
  check: "✅",
  done: "✅",
  listo: "✅",
  complete: "✅",
  cross: "❌",
  wrong: "❌",
  warning: "⚠️",
  alert: "⚠️",
  advertencia: "⚠️",
  question: "❓",
  pregunta: "❓",
  exclamation: "❗",
  info: "ℹ️",
  hundred: "💯",
  cien: "💯",

  // Animals
  dog: "🐶",
  puppy: "🐶",
  perro: "🐶",
  cat: "🐱",
  kitty: "🐱",
  gato: "🐱",
  mouse: "🐭",
  raton: "🐭",
  rabbit: "🐰",
  conejo: "🐰",
  fox: "🦊",
  zorro: "🦊",
  bear: "🐻",
  oso: "🐻",
  panda: "🐼",
  koala: "🐨",
  tiger: "🐯",
  tigre: "🐯",
  lion: "🦁",
  leon: "🦁",
  cow: "🐮",
  vaca: "🐮",
  pig: "🐷",
  cerdo: "🐷",
  frog: "🐸",
  rana: "🐸",
  monkey: "🐵",
  mono: "🐵",
  chicken: "🐔",
  pollo: "🐔",
  bird: "🐦",
  pajaro: "🐦",
  penguin: "🐧",
  pinguino: "🐧",
  fish: "🐟",
  pez: "🐟",
  shark: "🦈",
  tiburon: "🦈",
  whale: "🐋",
  ballena: "🐋",
  dolphin: "🐬",
  delfin: "🐬",
  octopus: "🐙",
  pulpo: "🐙",
  butterfly: "🦋",
  mariposa: "🦋",
  bee: "🐝",
  abeja: "🐝",
  bug: "🐛",
  bicho: "🐛",
  spider: "🕷️",
  arana: "🕷️",
  snake: "🐍",
  serpiente: "🐍",
  turtle: "🐢",
  tortuga: "🐢",
  horse: "🐴",
  caballo: "🐴",
  unicorn: "🦄",
  unicornio: "🦄",
  dragon: "🐉",

  // Vehicles & Transport
  car: "🚗",
  carro: "🚗",
  coche: "🚗",
  auto: "🚗",
  taxi: "🚕",
  bus: "🚌",
  autobus: "🚌",
  truck: "🚚",
  camion: "🚚",
  ambulance: "🚑",
  ambulancia: "🚑",
  police: "🚓",
  policia: "🚓",
  bike: "🚲",
  bicicleta: "🚲",
  motorcycle: "🏍️",
  moto: "🏍️",
  train: "🚂",
  tren: "🚂",
  plane: "✈️",
  avion: "✈️",
  helicopter: "🚁",
  helicoptero: "🚁",
  rocket: "🚀",
  cohete: "🚀",
  ship: "🚢",
  barco: "🚢",
  boat: "⛵",
  bote: "⛵",

  // Food & Drink
  apple: "🍎",
  manzana: "🍎",
  banana: "🍌",
  platano: "🍌",
  orange: "🍊",
  naranja: "🍊",
  lemon: "🍋",
  limon: "🍋",
  grape: "🍇",
  uva: "🍇",
  strawberry: "🍓",
  fresa: "🍓",
  watermelon: "🍉",
  sandia: "🍉",
  peach: "🍑",
  durazno: "🍑",
  cherry: "🍒",
  cereza: "🍒",
  tomato: "🍅",
  tomate: "🍅",
  corn: "🌽",
  maiz: "🌽",
  carrot: "🥕",
  zanahoria: "🥕",
  bread: "🍞",
  pan: "🍞",
  cheese: "🧀",
  queso: "🧀",
  egg: "🥚",
  huevo: "🥚",
  pizza: "🍕",
  burger: "🍔",
  hamburguesa: "🍔",
  fries: "🍟",
  papas: "🍟",
  hotdog: "🌭",
  taco: "🌮",
  burrito: "🌯",
  sushi: "🍣",
  ramen: "🍜",
  rice: "🍚",
  arroz: "🍚",
  pasta: "🍝",
  soup: "🍲",
  sopa: "🍲",
  salad: "🥗",
  ensalada: "🥗",
  popcorn: "🍿",
  candy: "🍬",
  dulce: "🍬",
  chocolate: "🍫",
  cookie: "🍪",
  galleta: "🍪",
  cake: "🎂",
  pastel: "🎂",
  ice: "🍦",
  helado: "🍦",
  donut: "🍩",
  dona: "🍩",
  coffee: "☕",
  cafe: "☕",
  tea: "🍵",
  te: "🍵",
  beer: "🍺",
  cerveza: "🍺",
  wine: "🍷",
  vino: "🍷",
  cocktail: "🍹",
  water: "💧",
  agua: "💧",

  // Nature & Weather
  sun: "☀️",
  sunny: "☀️",
  sol: "☀️",
  moon: "🌙",
  luna: "🌙",
  night: "🌙",
  cloud: "☁️",
  nube: "☁️",
  rain: "🌧️",
  lluvia: "🌧️",
  snow: "❄️",
  nieve: "❄️",
  thunder: "⚡",
  rayo: "⚡",
  rainbow: "🌈",
  arcoiris: "🌈",
  tree: "🌳",
  arbol: "🌳",
  flower: "🌸",
  flor: "🌸",
  rose: "🌹",
  rosa: "🌹",
  leaf: "🍃",
  hoja: "🍃",
  cactus: "🌵",
  palm: "🌴",
  palmera: "🌴",
  mountain: "⛰️",
  montana: "⛰️",
  volcano: "🌋",
  volcan: "🌋",
  beach: "🏖️",
  playa: "🏖️",
  ocean: "🌊",
  oceano: "🌊",
  waves: "🌊",
  ola: "🌊",
  earth: "🌍",
  tierra: "🌍",
  world: "🌍",
  mundo: "🌍",

  // Objects & Tech
  laptop: "💻",
  computer: "💻",
  computadora: "💻",
  phone: "📱",
  telefono: "📱",
  tablet: "📱",
  keyboard: "⌨️",
  teclado: "⌨️",
  cursor: "🖱️",
  printer: "🖨️",
  impresora: "🖨️",
  camera: "📷",
  camara: "📷",
  video: "📹",
  tv: "📺",
  television: "📺",
  radio: "📻",
  speaker: "🔊",
  headphone: "🎧",
  audifonos: "🎧",
  microphone: "🎤",
  microfono: "🎤",
  battery: "🔋",
  bateria: "🔋",
  plug: "🔌",
  bulb: "💡",
  bombilla: "💡",
  idea: "💡",
  flashlight: "🔦",
  linterna: "🔦",
  book: "📚",
  libro: "📚",
  notebook: "📓",
  cuaderno: "📓",
  pen: "🖊️",
  pluma: "🖊️",
  pencil: "✏️",
  lapiz: "✏️",
  memo: "📝",
  note: "📝",
  nota: "📝",
  folder: "📁",
  carpeta: "📁",
  file: "📄",
  archivo: "📄",
  clip: "📎",
  scissors: "✂️",
  tijeras: "✂️",
  ruler: "📏",
  regla: "📏",
  pin: "📌",
  pushpin: "📌",
  calendar: "📅",
  calendario: "📅",
  clock: "⏰",
  reloj: "⏰",
  hourglass: "⏳",
  alarm: "⏰",
  alarma: "⏰",
  email: "📧",
  correo: "📧",
  mail: "✉️",
  carta: "✉️",
  package: "📦",
  paquete: "📦",
  box: "📦",
  caja: "📦",
  bag: "👜",
  bolsa: "👜",
  backpack: "🎒",
  mochila: "🎒",
  glasses: "👓",
  lentes: "👓",
  umbrella: "☂️",
  paraguas: "☂️",
  key: "🔑",
  llave: "🔑",
  lock: "🔒",
  candado: "🔒",
  hammer: "🔨",
  martillo: "🔨",
  wrench: "🔧",
  tool: "🛠️",
  herramienta: "🛠️",

  // Money & Business
  money: "💰",
  dinero: "💰",
  dollar: "💵",
  euro: "💶",
  credit: "💳",
  tarjeta: "💳",
  card: "💳",
  gem: "💎",
  diamante: "💎",
  crown: "👑",
  corona: "👑",
  trophy: "🏆",
  trofeo: "🏆",
  medal: "🥇",
  medalla: "🥇",
  target: "🎯",
  objetivo: "🎯",
  chart: "📊",
  grafico: "📊",
  graph: "📈",
  trending: "📈",

  // Sports & Activities
  soccer: "⚽",
  futbol: "⚽",
  basketball: "🏀",
  football: "🏈",
  baseball: "⚾",
  tennis: "🎾",
  volleyball: "🏐",
  golf: "⛳",
  bowling: "🎳",
  pool: "🎱",
  ping: "🏓",
  badminton: "🏸",
  boxing: "🥊",
  martial: "🥋",
  ski: "⛷️",
  snowboard: "🏂",
  surf: "🏄",
  swim: "🏊",
  nadar: "🏊",
  run: "🏃",
  correr: "🏃",
  walk: "🚶",
  caminar: "🚶",
  dance: "💃",
  bailar: "💃",
  yoga: "🧘",
  gym: "🏋️",
  gimnasio: "🏋️",

  // Entertainment
  party: "🎉",
  fiesta: "🎉",
  celebrate: "🎉",
  gift: "🎁",
  regalo: "🎁",
  balloon: "🎈",
  globo: "🎈",
  confetti: "🎊",
  music: "🎵",
  musica: "🎵",
  guitar: "🎸",
  guitarra: "🎸",
  piano: "🎹",
  drum: "🥁",
  tambor: "🥁",
  movie: "🎬",
  pelicula: "🎬",
  ticket: "🎟️",
  boleto: "🎟️",
  game: "🎮",
  juego: "🎮",
  dice: "🎲",
  dado: "🎲",
  puzzle: "🧩",
  art: "🎨",
  arte: "🎨",
  paint: "🖌️",
  pintura: "🖌️",
  theater: "🎭",
  teatro: "🎭",
  circus: "🎪",
  circo: "🎪",

  // Buildings & Places
  house: "🏠",
  casa: "🏠",
  home: "🏠",
  hogar: "🏠",
  building: "🏢",
  edificio: "🏢",
  office: "🏢",
  oficina: "🏢",
  hospital: "🏥",
  school: "🏫",
  escuela: "🏫",
  university: "🎓",
  universidad: "🎓",
  church: "⛪",
  iglesia: "⛪",
  mosque: "🕌",
  mezquita: "🕌",
  temple: "🛕",
  templo: "🛕",
  castle: "🏰",
  castillo: "🏰",
  stadium: "🏟️",
  estadio: "🏟️",
  store: "🏪",
  tienda: "🏪",
  shop: "🛍️",
  hotel: "🏨",
  bank: "🏦",
  banco: "🏦",
  factory: "🏭",
  fabrica: "🏭",
  airport: "✈️",
  aeropuerto: "✈️",
  station: "🚉",
  estacion: "🚉",

  // People & Body
  baby: "👶",
  bebe: "👶",
  boy: "👦",
  nino: "👦",
  girl: "👧",
  nina: "👧",
  man: "👨",
  hombre: "👨",
  woman: "👩",
  mujer: "👩",
  family: "👨‍👩‍👧‍👦",
  familia: "👨‍👩‍👧‍👦",
  couple: "👫",
  pareja: "👫",
  friends: "👯",
  amigos: "👯",
  king: "🤴",
  rey: "🤴",
  queen: "👸",
  reina: "👸",
  princess: "👸",
  princesa: "👸",
  santa: "🎅",
  eyes: "👀",
  ojos: "👀",
  brain: "🧠",
  cerebro: "🧠",
  muscle: "💪",
  musculo: "💪",
  bone: "🦴",
  hueso: "🦴",

  // Fantasy & Spooky
  skull: "💀",
  calavera: "💀",
  ghost: "👻",
  fantasma: "👻",
  alien: "👽",
  robot: "🤖",
  poop: "💩",
  caca: "💩",
  zombie: "🧟",
  vampire: "🧛",
  vampiro: "🧛",
  witch: "🧙",
  bruja: "🧙",
  fairy: "🧚",
  hada: "🧚",
  mermaid: "🧜",
  sirena: "🧜",
  ninja: "🥷",
  pirate: "🏴‍☠️",
  pirata: "🏴‍☠️",

  // Misc
  zzz: "💤",
  sleep: "💤",
  dormir: "💤",
  boom: "💥",
  explosion: "💥",
  dizzy: "💫",
  sweat: "💦",
  sudor: "💦",
  hole: "🕳️",
  speech: "💬",
  thought: "💭",
  anger: "💢",
  link: "🔗",
  url: "🔗",
  enlace: "🔗",
  search: "🔍",
  buscar: "🔍",
  zoom: "🔎",
  new: "🆕",
  nuevo: "🆕",
  free: "🆓",
  gratis: "🆓",
  top: "🔝",
  soon: "🔜",
  pronto: "🔜",
  back: "🔙",
  end: "🔚",
  on: "🔛",
  genial: "🆒",
  sos: "🆘",
  up: "⬆️",
  down: "⬇️",
  left: "⬅️",
  right: "➡️",
  recycle: "♻️",
  reciclar: "♻️",
  infinity: "♾️",
  infinito: "♾️",
};

const EMOJI_KEYWORDS = new Set(Object.keys(EMOJI_SHORTCUTS));

export function replaceEmojiShortcuts(text: string): string {
  if (!text.includes(".") && !text.includes(",") && !text.includes("!") && 
      !text.includes("?") && !text.includes(";") && !text.includes(":")) {
    return text;
  }

  let result = text;
  
  for (const keyword of EMOJI_KEYWORDS) {
    const emoji = EMOJI_SHORTCUTS[keyword];
    const pattern = new RegExp(`\\b(${keyword})(?!\\s${emoji})\\b`, "gi");
    
    result = result.replace(pattern, (match) => {
      return match + " " + emoji;
    });
  }
  
  return result;
}

export function getEmojiForShortcut(shortcut: string): string | null {
  return EMOJI_SHORTCUTS[shortcut.toLowerCase()] || null;
}
