const EMOJI_SHORTCUTS: Record<string, string> = {
  happy: "😀",
  smile: "😀",
  feliz: "😀",
  laugh: "😂",
  lol: "😂",
  risa: "😂",
  love: "😍",
  amor: "😍",
  think: "🤔",
  hmm: "🤔",
  pensando: "🤔",
  ok: "👍",
  good: "👍",
  yes: "👍",
  bien: "👍",
  bad: "👎",
  no: "👎",
  mal: "👎",
  heart: "❤️",
  corazon: "❤️",
  fire: "🔥",
  fuego: "🔥",
  hot: "🔥",
  sparkles: "✨",
  magic: "✨",
  brillos: "✨",
  party: "🎉",
  fiesta: "🎉",
  celebrate: "🎉",
  idea: "💡",
  bombilla: "💡",
  warning: "⚠️",
  alert: "⚠️",
  advertencia: "⚠️",
  check: "✅",
  done: "✅",
  listo: "✅",
  complete: "✅",
  cross: "❌",
  wrong: "❌",
  error: "❌",
  memo: "📝",
  note: "📝",
  nota: "📝",
  write: "📝",
  clip: "📎",
  attach: "📎",
  adjunto: "📎",
  link: "🔗",
  url: "🔗",
  enlace: "🔗",
  pin: "📌",
  important: "📌",
  chincheta: "📌",
  rocket: "🚀",
  cohete: "🚀",
  fast: "🚀",
  laptop: "💻",
  computer: "💻",
  code: "💻",
  computadora: "💻",
  dog: "🐶",
  puppy: "🐶",
  perro: "🐶",
  cat: "🐱",
  kitty: "🐱",
  gato: "🐱",
  star: "⭐",
  estrella: "⭐",
  favorite: "⭐",
  rainbow: "🌈",
  arcoiris: "🌈",
  colors: "🌈",
  sun: "☀️",
  sunny: "☀️",
  sol: "☀️",
  moon: "🌙",
  luna: "🌙",
  night: "🌙",
  strong: "💪",
  power: "💪",
  fuerza: "💪",
  pray: "🙏",
  thanks: "🙏",
  gracias: "🙏",
  please: "🙏",
  wave: "👋",
  hello: "👋",
  bye: "👋",
  hola: "👋",
  adios: "👋",
  cry: "😢",
  sad: "😢",
  triste: "😢",
  angry: "😠",
  enojado: "😠",
  cool: "😎",
  sunglasses: "😎",
  wink: "😉",
  guino: "😉",
  kiss: "😘",
  beso: "😘",
  clap: "👏",
  aplausos: "👏",
  eyes: "👀",
  ojos: "👀",
  brain: "🧠",
  cerebro: "🧠",
  coffee: "☕",
  cafe: "☕",
  beer: "🍺",
  cerveza: "🍺",
  pizza: "🍕",
  burger: "🍔",
  hamburguesa: "🍔",
  taco: "🌮",
  cake: "🎂",
  pastel: "🎂",
  gift: "🎁",
  regalo: "🎁",
  music: "🎵",
  musica: "🎵",
  movie: "🎬",
  pelicula: "🎬",
  camera: "📷",
  camara: "📷",
  phone: "📱",
  telefono: "📱",
  email: "📧",
  correo: "📧",
  clock: "⏰",
  reloj: "⏰",
  money: "💰",
  dinero: "💰",
  dollar: "💵",
  gem: "💎",
  diamante: "💎",
  crown: "👑",
  corona: "👑",
  trophy: "🏆",
  trofeo: "🏆",
  medal: "🥇",
  medalla: "🥇",
  target: "🎯",
  objetivo: "🎯",
  key: "🔑",
  llave: "🔑",
  lock: "🔒",
  candado: "🔒",
  bug: "🐛",
  bichos: "🐛",
  skull: "💀",
  calavera: "💀",
  ghost: "👻",
  fantasma: "👻",
  alien: "👽",
  robot: "🤖",
  poop: "💩",
  caca: "💩",
  hundred: "💯",
  cien: "💯",
  zzz: "💤",
  sleep: "💤",
  dormir: "💤",
};

export function replaceEmojiShortcuts(text: string): string {
  const pattern = /\b(\w+)([.,!?;:])(?=\s|$)/g;
  
  return text.replace(pattern, (match, word, punctuation) => {
    const emoji = EMOJI_SHORTCUTS[word.toLowerCase()];
    if (emoji) {
      return emoji + punctuation;
    }
    return match;
  });
}

export function getEmojiForShortcut(shortcut: string): string | null {
  return EMOJI_SHORTCUTS[shortcut.toLowerCase()] || null;
}
